class RecordError(Exception):
    pass


class RecordNotFoundError(RecordError):
    pass
